---
title: "feature_importance_plot_xgboost"
author: "Yue Zhang"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse)
```

```{r}
df1 <- read_csv(here::here("results/model_1a_xgboost_feature_importance.csv"),
                col_types = cols())
df2 <- read_csv(here::here("results/model_1b_xgboost_feature_importance.csv"),
                col_types = cols())
```


```{r}
df_pre_long <- df1 %>% 
  # except state
  select(-contains("state")) %>%
  pivot_longer(everything()) %>% 
  group_by(name) %>% 
  summarise(
    # summarise by median
    importance_val = median(value),
    std = sd(value)/sqrt(n()),
    q1 = quantile(value, 0.25),
    q2 = quantile(value, 0.75)
  ) %>% 
  mutate(time = "pre-mandate")

df_post_long <- df2 %>% 
  select(-contains("state")) %>%
  pivot_longer(everything()) %>% 
  group_by(name) %>% 
  summarise(
    importance_val = median(value),
    std = sd(value)/sqrt(n()),
    q1 = quantile(value, 0.25),
    q2 = quantile(value, 0.75)
  ) %>% 
  mutate(time = "mandate")
```



```{r}
df <- df_pre_long %>% 
  arrange(-importance_val) %>% 
  bind_rows(df_post_long %>% arrange(-importance_val)) %>% 
  group_by(time) %>% 
  slice(1:10) %>% 
  ungroup() %>%

  mutate(group_var = case_when(
    str_detect(name, "i2|i9|i11") ~ "Contact behaviour",
    str_detect(name, "age|house|employ|gender") ~ "Demographics",
    str_detect(name, "cantril") ~ "Wellbeing",
    str_detect(name, "PHQ") ~ "Mental health",
    str_detect(name, "r1") ~ "Perception of illness threat",
    str_detect(name, "week") ~ "Time",
    str_detect(name, "WCR") ~ "Trust in government",
    str_detect(name, "d1") ~ "Comorbidities",
    str_detect(name, "protective") ~ "Self protective behaviours",
    TRUE ~ "Others"
  )) %>%
  mutate(name = fct_reorder(name, importance_val)) %>% 
  mutate(time = ifelse(time=="mandate", "During mandates", "Before mandates"))

df$importance_val[df$time=="Before mandates"] <- -df$importance_val[df$time=="Before mandates"]
df$q1[df$time=="Before mandates"] <- -df$q1[df$time=="Before mandates"]
df$q2[df$time=="Before mandates"] <- -df$q2[df$time=="Before mandates"]

df_tmp <- df %>% 
  group_by(time) %>% 
  filter(row_number() == 1) %>% 
  mutate(importance_val = ifelse(time == "During mandates", 0.17, -0.17))

```

```{r, warning=FALSE}
labels_original <- df %>% 
  pull(name) %>% 
  levels()

labels <- labels_original %>% 
  str_replace_all("_", " ") %>% 
  str_to_title() 

labels <- str_replace(labels, " Nomask Scale", "")
labels[str_detect(labels, "State")] <- str_c(labels[str_detect(labels, "State")], ")")
labels[str_detect(labels, "State")] <- str_replace(labels[str_detect(labels, "State")], "State ", "State (")

labels[str_detect(labels, "I11 Health")] <- str_c(labels[str_detect(labels, "I11 Health")], " To Isolate")
labels[str_detect(labels, "I11 Health")] <- str_replace(labels[str_detect(labels, "I11 Health")], "I11 Health ", "")
labels[str_detect(labels, "I9 Health Yes")] <- "Will Isolate If Unwell"
labels[str_detect(labels, "D1")] <- "Has Comorbidities"
labels[str_detect(labels, "R1")] <- "Perceived Severity"
labels[str_detect(labels, "Wcrex1")] <- "Confidence In Response (Very Well)"
labels[str_detect(labels, "Wcrex2")] <- "Government Transparency (A lot of confidence)"
labels[str_detect(labels, "I9 Health Not Sure")] <- "Isolate If Unwell (Not Sure)"
labels[str_detect(labels, "Phq4 4")] <- "Feeling Depressed (Prefer not to say)"
labels[str_detect(labels, "Phq4 3")] <- "Feeling Nervous (N/A)"

```

```{r, warning=FALSE}
df %>%
  ggplot(aes(x = importance_val, y = name, fill = group_var)) +
  geom_col(alpha = 0.8) +
  
  geom_point(data = df_tmp, colour = NA) +
  
  geom_errorbar(aes(xmin = q1, xmax = q2), width = 0.4, color = "grey20") +
  facet_wrap(~time, scale = "free_x") +
  
  scale_x_continuous(expand = c(0, 0), 
                     labels = function(x) signif(abs(x), 3)) +
  scale_y_discrete(labels = labels) +
  
  scale_fill_brewer(palette = "Set3") + 
  labs(y = NULL, x = "Feature Importance (Median & IQR)", fill = "Category") +
  theme_bw() +
  theme(panel.spacing.x = unit(0, "mm"),
        legend.position = "bottom",
        legend.text = element_text(size = 8))
```
