---
title: "Test table"
author: "Yue Zhang"
output: 
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load(tidyverse, kableExtra, here, glue)
```

```{r}
get_model_results <- function(){
  # read data
  df <- read_csv(here::here(glue::glue("results/final_model_test_metrics.csv")),
                 col_types = cols())
  
  round_to <- 3
  models <- c("XGBoost", "Random Forest")
  df <- df %>% 
    # process all test metrics
    mutate(precision = round(test_precision, round_to),
           recall = round(test_recall, round_to),
           roc_auc = round(test_roc_auc, round_to),
           accuracy = round(test_accuracy, round_to),
           f1 = round(test_f1, round_to)) %>% 
    # delete original test column
    select(-contains("test_")) %>% 
    # set model type
    mutate(target = ifelse(str_detect(model_number, "_1"), "face mask", "protect behaviour"),
           # set before/after mandate
           model_group = case_when(str_detect(model_number, "a") ~ "before mandate",
                                   str_detect(model_number, "b") ~ "after mandate",
                                   TRUE ~ NA_character_),
           model_group = str_c(model_group, target, sep="-")) %>% 
    
    arrange(model_group) %>% 
    drop_na() %>% 
    
    rename(` ` = model_type,
      Precision = precision,
      Recall = recall,
      `AUC` = roc_auc,
      Accuracy = accuracy,
      F1 = f1)
  
  return(df)
}

```

```{r, message=FALSE}
res <- get_model_results()
```

```{r}
res %>% 
  select(-model_group, -target, -model_number) %>%
  select(` `, `AUC`, everything()) %>% 
  kable(booktabs=TRUE, 
        caption="Metric validation on test data.",
        align="lrrrrr") %>% 
  pack_rows(index=table(res$model_group)) %>% 
  kable_styling(latex_options = c("striped", "hold_position", "scale_up"))
```